twa-web-docs
cambridge-cares/TheWorldAvatar pull request #1043
Opened 2023-12-11 14:41 UTC by mdhillman

This PR brings in some documentation on how to better structure URLs so that they will still resolve correctly when placed behind redirects from [theworldavatar.io](https://theworldavatar.io) website.

It also adds a simple testing ground to allow users to run a local NGINX instance with a redirect to their external service, allowing them to test their URLs before requesting a redirect from theworldavatar.io.

2023-12-13 11:09 UTC, Ushcode approved these changes

2023-12-14 12:19 UTC, Ushcode approved these changes

2023-12-14 14:47 UTC, gpeb2 commented on web/docs/README.md
> +To run it, simply add the URL for your external container (which can be running) to a `.env` following the format below, then run the `run.sh` script. This should spin up a local NGINX container with
```run.sh``` has been renamed.

2023-12-14 14:47 UTC, gpeb2 commented on web/docs/README.md
> +The committed `docker-compose.yml` file also spins up a simple web server in it's own container hosting some static content to display an example of which URL types will and won't work. You can acces
Might be bettered as numbered steps.

2023-12-14 15:05 UTC, Ushcode requested changes

2023-12-14 15:05 UTC, Ushcode commented on web/docs/url-testing/start.sh
> +docker compose -f ./docker-compose.yml up -d --build
```suggestion
docker compose -f ./docker-compose.yml up -d --build || exit 1
```

Exit if the docker compose fails

2023-12-14 17:22 UTC, gpeb2 approved these changes
I'd have probably used numbers rather than bullet points for the testing steps but it's fine as it is.

2023-12-15 10:45 UTC, Ushcode approved these changes

2023-12-15 10:45 UTC, merged