Zeolite abox writer agent
cambridge-cares/TheWorldAvatar pull request #1171
Opened 2024-04-24 09:01 UTC by paul-cares

A new feature: an ontology and knowledge graph for zeolitic materials.
Contains two new ontologies: OntoCrystal, OntoZeolite.

The OntoCrystal can be used separately to represent crystal information of any crystalline material.

2024-04-24 18:10 UTC, sm453 requested changes

2024-04-30 04:26 UTC, paul-cares commented on Agents/ZeoliteAgent/zeoliteaboxwriteragent/upload_cryst.bat
> +  set BASE="http://178.128.105.213:3838/blazegraph-dev/ui/namespace/"
I move all configuration to the main bat file and added a note in README

2024-04-30 04:30 UTC, paul-cares commented on JPS_Ontology/ontology/ontozeolite/ontozeolite.owl
> +        <rdfs:comment rdf:datatype="http://www.w3.org/2001/XMLSchema#string">A set of characteristics to describe the geometrical and/or topological properties of a material</rdfs:comment>
Yes, it is difficult

2024-04-30 04:32 UTC, paul-cares commented on JPS_Ontology/ontology/ontozeolite/ontocrystal.owl
Yes, now it is hard now.
I expect that the manuscript may require changes, so the final abox to be uploaded as supporting information can be changed later. I keep track of such wish list, thank you for pointing it out.

2024-04-30 04:32 UTC, paul-cares commented on Agents/ZeoliteAgent/README.md
> +- The input data (stored in the directory `ontozeolite`)
This correction is obsolete, as we discussed. 
An example file in github and full data in dropbox.

2024-04-30 09:25 UTC, sm453 commented on Agents/ZeoliteAgent/README.md
> +- The input data (stored in the directory `ontozeolite`)
While our discussion did indeed show that the above correction is obsolete, two further points arose:
1) Please replace `ontozeolite` with `Agents/ZeoliteAgent/zeoliteaboxwriteragent/ontozeolite/`, otherwise it is not obvious.
2) Please add a sentence that clarifies that that folder only contains a single example file as a proof of concept. It might also be useful to include a link to the preprint as a hint how to populate the folder with serious data.

2024-04-30 14:55 UTC, paul-cares commented on Agents/ZeoliteAgent/README.md
> +- The input data (stored in the directory `ontozeolite`)
Done

2024-05-01 08:40 UTC, sm453 approved these changes

2024-05-02 02:55 UTC, merged