Dev 1750 building floor
cambridge-cares/TheWorldAvatar pull request #1202
Opened 2024-05-10 03:11 UTC by yjytt59

Building Floor Agent aims to integrate number of floors to the 3D building data.

2024-05-14 07:03 UTC, sm453 commented
Looks like #1131 will need to be merged before this PR.

2024-05-14 10:56 UTC, sm453 commented
Given the situation with #1131, the best course of action seems to be to revert all changes relating to the GFA agent and to `dev-singapore-stack` on the present branch.

2024-05-16 03:29 UTC, yjytt59 commented
#1131 has been separated in to two agents now, one is the Building Floor Agent, which is only focused on integrated number of floors to the 3D building. The other is new GFA agent, which aims to calculate the GFA and construction cost. I will pull a new request of new GFA agent soon.

2024-06-03 08:41 UTC, kok-foong commented on Agents/BuildingFloorAgent/src/main/resources/buildingfloor.odba
> +            twa:NumberOfFloors/{strval} a env:FloorCat{storeys_above_ground_cat} ;
I find defining the rdf type like this is very risky and prone to errors as the values of storeys_above_ground_cat relies heavily on the success of some non-trivial queries/logic executed by the agent.

2024-06-11 08:28 UTC, sm453 requested changes

2024-06-11 08:28 UTC, sm453 commented on Agents/BuildingFloorAgent/src/main/resources/HDBPropertyInformation.csv
Version control is for code, not for data! Please remove this file (and promise never to commit anything like that ever again).

Instead, please upload the file to an appropriate subfolder of `dropbox\IRP3 CAPRICORN shared folder\_TWA_Shared_Data`, and add this path to your main readme file, together with an explanation of what this is and why it is needed.

2024-06-12 08:39 UTC, sm453 approved these changes
Any change outside the `BuildingFloorAgent/` folder has been removed - this is good.

Remaining issues as discussed to be addressed by @kok-foong on a separate branch.

2024-06-13 03:54 UTC, merged