Dev 1793 extend ontology for acph on lab dashboard
cambridge-cares/TheWorldAvatar pull request #1211
Opened 2024-05-19 10:36 UTC by Michael-TeguhLaksana

Added the ACPH and its property for the air change per hour in the CARES lab. I haven't added the room volume related concepts yet, as  depending on how its calculated, it may require different representations.

2024-05-25 16:07 UTC, Abyssus1010 requested changes

2024-05-25 16:07 UTC, Abyssus1010 commented on JPS_Ontology/ontology/ontodevice/OntoDevice.csv
> +hasAirExchangeRate,Object Property,https://www.theworldavatar.com/kg/ontodevice/hasQuantity,IS-A,https://saref.etsi.org/core/HVAC,http://www.theworldavatar.com/ontology/ontodevice/AIrChangePerHour,,A
is it ontodevice:AirChangePerHour or ontobms:AirChangePerHour? 

ontodevice:hasAirExchangeRate should be defined under ontodevice right?

2024-05-25 16:15 UTC, Abyssus1010 commented on JPS_Ontology/ontology/ontodevice/OntoDevice.csv
> +hasAirExchangeRate,Object Property,https://www.theworldavatar.com/kg/ontodevice/hasQuantity,IS-A,https://saref.etsi.org/core/HVAC,http://www.theworldavatar.com/ontology/ontodevice/AIrChangePerHour,,A
Another comment: to me, it will make more sense to say that a room or zone has air exchange rate, rather than a hvac device having air exchange rate.

2024-05-25 16:32 UTC, Abyssus1010 commented
I shifted hasAirExchangeRate to ontobms instead and did some other corrections to the definitions. I also modified the domain of hasAirExchangeRate to bot:Zone instead of saref:HVAC as ACH is a metric used to describe the ventilation rate of a space, indicating how many times the air within that space is replaced in one hour. It is not used to describe the operating property of a HVAC device.

2024-05-25 16:32 UTC, Abyssus1010 commented
@Michael-TeguhLaksana Please review and let me know if it is okay

2024-05-27 02:29 UTC, Michael-TeguhLaksana commented
Yes, its supposed to be ontobms:hasAirExchangeRate, I somehow put it wrong there. Seems to make sense now, I think its correct.

2024-05-27 06:02 UTC, Abyssus1010 approved these changes

2024-05-27 06:02 UTC, merged