dev-marie-webpage: Zeolite QA and visualisation
cambridge-cares/TheWorldAvatar pull request #1224
Opened 2024-05-24 09:11 UTC by picas9dan

2024-05-29 13:02 UTC, sm453 requested changes
As before, the most glaring issue is the total absence of any documentation. Given that this PR adds substantial new functionality, can you please substantially (i.e. in a way that reflects the expansion in functionality) expand the main readme file(s)?

2024-05-29 14:34 UTC, picas9dan commented on QuestionAnswering/QA_SEQ2SEQ/deployment/triton/model_repository/seq2seq_chemistry/1/model.json
> +    "model_path": "picas9dan/20240516_8_onnx_8bit"
By default, the code will interpret the `model_path` argument as the identifier on HuggingFace Hub, which is [here](https://huggingface.co/picas9dan/20240516_8_onnx_8bit). Currently the code is not set up to load model weights from local filesystem. 

I'll update the README to reflect this information.

2024-05-30 02:06 UTC, picas9dan commented on QuestionAnswering/QA_SEQ2SEQ/deployment/triton/model_repository/seq2seq_chemistry/1/model.json
> +    "model_path": "picas9dan/20240516_8_onnx_8bit"
I've updated the README file at `deployment/triton` to reflect what model type is supported by the code, how to convert the model weights to the required format, and the platform to host the weights.

2024-05-30 02:08 UTC, picas9dan commented on QuestionAnswering/QA_SEQ2SEQ/deployment/fastapi_app/api/adv_search.py
> +            SERVICE <http://178.128.105.213:3838/blazegraph/namespace/ontospecies/sparql> {{
I've replaced this with the value of an environment variable.

2024-05-30 02:12 UTC, picas9dan commented
> As before, the most glaring issue is the total absence of any documentation. Given that this PR adds substantial new functionality, can you please substantially (i.e. in a way that reflects the expansion in functionality) expand the main readme file(s)?

I have updated `deployment/fastapi_app/README.md` with a description of all the features available.

2024-05-30 14:00 UTC, sm453 approved these changes

2024-05-31 06:45 UTC, merged