1773 timeline app
cambridge-cares/TheWorldAvatar pull request #1313
Opened 2024-08-16 04:02 UTC by sandradeng20

Version 1 of the timeline app, which contains the following functionalities:
- User login
- Visualise trajectory of the logged in user
- Record sensor data

2024-08-22 14:22 UTC, sm453 requested changes

2024-08-22 14:22 UTC, sm453 commented on Apps/TimelineApp/core/login/README.md
You may want to add links/references to this (and perhaps other modules) to the top-level `Apps/TimelineApp/README.md`. Otherwise one won't really know that they are there...

2024-08-22 14:22 UTC, sm453 commented on Apps/TimelineApp/core/sensor/src/androidTest/java/uk/ac/cam/cares/jps/sensor/UnsentDataTest.java
Is this still relevant?

2024-09-05 06:47 UTC, sandradeng20 commented on Apps/TimelineApp/feature/user/src/main/java/uk/ac/cam/cares/jps/user/SensorSettingFragment.java
> +    private boolean allToggledOn = false;
the fragment is an UI level component and should not host any states. States should be managed by ViewModel.

2024-09-05 06:47 UTC, sandradeng20 commented on Apps/TimelineApp/feature/user/src/main/java/uk/ac/cam/cares/jps/user/SensorSettingFragment.java
> +        sensorItems.add(new SensorItem("Microphone", "Capture sound levels.", sensorManager.getSensorHandler(SensorType.SOUND)));
SensorManager and SensorHandler are source level component and should not be directly accessed in UI level. It should go through the structure `source -> repository -> viewmodel -> ui` to achieve a modularized and decoupled design. Besides, there is no need to get the handler instance here.

2024-09-05 06:47 UTC, sandradeng20 commented on Apps/TimelineApp/feature/user/src/main/java/uk/ac/cam/cares/jps/user/SensorSettingFragment.java
> +            toggleAllBtn.setText(allToggledOn ? "Toggle Off" : "Toggle All");
it makes more sense to put `allToggledOn` in ViewModel and only update the `allToggledOn` here. Then listen to the `allToggledOn` live data to do all the ui update. Can refer to line153.

2024-09-05 06:57 UTC, sandradeng20 commented on Apps/TimelineApp/feature/user/src/main/java/uk/ac/cam/cares/jps/user/SensorSettingFragment.java
> +        binding.toggleAllBtn.setText("Toggle All");
"Toggle All" should use string resource instead of string constant

2024-09-06 06:42 UTC, katrinashonka commented on Apps/TimelineApp/core/sensor/src/main/java/uk/ac/cam/cares/jps/sensor/source/database/model/entity/LocationData.java
> +        this.verticalAccuracy = verticalAccuracy;
Yes, every data point in a trajectory can carry accuracy information, but whether it actually does depends on the availability of this data from the sensors/GPS signal strength. After reviewing API documentation, we've determined that accuracy values can be useful in filtering out noise in trajectory data. While not always precise on a point-by-point basis, they provide information that can help in refining the trajectory for certain use cases. Therefore, for now, we are keeping these values but will continue monitoring their usefulness in future iterations.

2024-09-06 06:48 UTC, katrinashonka commented on Apps/TimelineApp/build.gradle
Yes, they are necessary. Each module requires its own build.gradle file to properly define its namespace, dependencies, and specific build configurations.

2024-09-10 08:32 UTC, sm453 approved these changes
Please correct the three extensions in the readmes prior to merging the PR.

2024-09-10 08:32 UTC, sm453 commented on Apps/TimelineApp/README.md
> +Add the Mapbox public key to [developer_config.json](https://github.com/cambridge-cares/TheWorldAvatar/blob/main/Apps/TimelineApp/core/utils/src/main/res/values/developer_config.xml).
`.xml` instead of `.json`.

2024-09-10 08:32 UTC, sm453 commented on Apps/TimelineApp/README.md
> +Please add the stack address to `host_with_port` in [network_config.json](https://github.com/cambridge-cares/TheWorldAvatar/blob/main/Apps/TimelineApp/core/utils/src/main/res/values/network_config.xm
`.xml` instead of `.json`.

2024-09-10 08:32 UTC, sm453 commented on Apps/TimelineApp/core/utils/README.md
> +Please add the stack address to `host_with_port` in [network_config.json](https://github.com/cambridge-cares/TheWorldAvatar/blob/main/Apps/TimelineApp/core/utils/src/main/res/values/network_config.xm
`.xml` instead of `.json`.

2024-09-10 08:47 UTC, merged