34 dev energy density unit extension in ontouom
cambridge-cares/TheWorldAvatar pull request #373
Opened 2022-10-14 08:39 UTC by YiKaiTsai

2022-10-14 09:03 UTC, markushofmeister requested changes
Just looking at the units needed for OntoHeatNetwork: Is `EUR/t` already included in `OM` or did we just miss it?

2022-10-14 09:08 UTC, markushofmeister commented
@msff2: If I remember correctly, the newly created concepts would need to be added to the overall `om-2.0.rdf` file on `https://github.com/cambridge-cares/OM` (as well as Claudius - to ensure resolvability), right? If that's still the case:
1) Could you please guide Yi Kai through that (I am very sorry, but I doubt to remember all steps properly)
2) Does the changed base IRI of the additional concepts cause issues?

2022-10-14 09:09 UTC, sm453 requested changes
The unit "kilowattHourPerKilowatt" appears to be labelled "kilowatt hour per square metre". Please fix this.

2022-10-14 09:24 UTC, YiKaiTsai commented on JPS_Ontology/ontology/ontouom/kilowattHourPerKilowatt
> +    <om:hasDimension rdf:resource="&om;time-Dimension"/>
This is for Solarkataster, meant for specific yield.

2022-10-14 09:25 UTC, YiKaiTsai commented on JPS_Ontology/ontology/ontouom/euroPerHour
> +   </om:UnitDivision>
> Just looking at the units needed for OntoHeatNetwork: Is `EUR/t` already included in `OM` or did we just miss it?

EUR/t is already in OM as euroPerTonne.

2022-10-17 08:20 UTC, markushofmeister approved these changes

2022-10-17 08:29 UTC, msff2 approved these changes

2022-10-17 11:14 UTC, msff2 commented on JPS_Ontology/ontology/ontouom/euroPerHour
> +   </om:UnitDivision>
> > Currently we define all concepts using this unit solely as `Quantity` (e.g. revenue in time interval, cost in time interval); hence, there is no specific `subQuantity` and `UnitDimension` defined. Is this fine for now or shall that be amended? Same applies for `euroPerMegawattHour`
> 
> @sm453 @msff2 Is this fine for now or shall we create more specific `Sub-Quantities`? Looking at `https://raw.githubusercontent.com/cambridge-cares/OM/master/om-2.0.rdf`, I can see that there is already a `AmountOfMoneyPerArea` concept specified as subclass of `Quantity`. There are also the required `Unit` and `Dimension` concepts included. Following this example, it should be easy to create the corresponding concepts for `AmountOfMoneyPerTimeInterval` and `AmountOfMoneyPerEnergy`.

Seb wants us to put all Units of Measure ontology extensions in our OM fork, as this is an ideal approach to follow. I think it won't be a bad idea to ask [YiKaiTsai](https://github.com/YiKaiTsai) to create a more specific quantity for each new unit wherever required by analysing the Cost, AmountOfMoney and SpecificAmountOfMoney subclasses of Quantity and their relationships. We can postpone the migration to the OM fork until [YiKaiTsai](https://github.com/YiKaiTsai) completes this task.

2022-10-17 11:23 UTC, msff2 commented
> 



> @msff2: If I remember correctly, the newly created concepts would need to be added to the overall `om-2.0.rdf` file on `https://github.com/cambridge-cares/OM` (as well as Claudius - to ensure resolvability), right? If that's still the case:
> 
> 1. Could you please guide Yi Kai through that (I am very sorry, but I doubt to remember all steps properly)
> 2. Does the changed base IRI of the additional concepts cause issues?

Soon, we will include everything in om-2.0.rdf. Yes, [YiKaiTsai](https://github.com/YiKaiTsai) should put newly created classes/concepts in that file. Regarding my help or guidance, please read the previous comment on analysing existing subclasses of Quantity.

2022-10-27 11:19 UTC, sm453 requested changes
I believe in JPS_Ontology/ontology/ontouom/nanogramPerCubicMetre, a hasDimension node has been accidentally replaced with a URL string.

In JPS_Ontology/ontology/ontouom/EnergyPerArea, there are three nodes defining different aspects of the same class. Wouldn't it be preferable to merge these into one?

How come JPS_Ontology/ontology/ontouom/MassPerEnergy is treated so differently from others, e.g. JPS_Ontology/ontology/ontouom/HeatFluxDensity? Shouldn't it also have a value and a unit, etc.?

2022-10-27 13:44 UTC, msff2 approved these changes

2022-10-27 13:55 UTC, msff2 commented
> I believe in JPS_Ontology/ontology/ontouom/nanogramPerCubicMetre, a hasDimension node has been accidentally replaced with a URL string.

I agree with Seb's doubt and this needs to be fixed.

2022-10-27 13:59 UTC, msff2 commented
> In JPS_Ontology/ontology/ontouom/EnergyPerArea, there are three nodes defining different aspects of the same class. Wouldn't it be preferable to merge these into one?

Yes, these are different aspects of the same class and we can merge them. I think Yi has done it by following OM.

2022-10-27 14:24 UTC, msff2 commented
> How come JPS_Ontology/ontology/ontouom/MassPerEnergy is treated so differently from others, e.g. JPS_Ontology/ontology/ontouom/HeatFluxDensity? Shouldn't it also have a value and a unit, etc.?

Yes, I agree with Seb that, at the moment, you created a partial representation of MassPerEnergy. I think in doing this, you looked at the partial model like the following for Length:

  <owl:Class rdf:about="&om;Length">
    <rdfs:subClassOf>
      <owl:Restriction>
        <owl:onProperty rdf:resource="&om;hasDimension"/>
        <owl:hasValue rdf:resource="&om;length-Dimension"/>
      </owl:Restriction>
    </rdfs:subClassOf>
  </owl:Class>

But you didn't notice that the same class Length also has the following representation in the same om-2.0.rdf file.

<owl:Class rdf:about="&om;Length">
    <rdfs:subClassOf>
      <owl:Restriction>
        <owl:onProperty rdf:resource="&om;hasValue"/>
        <owl:allValuesFrom>
          <owl:Restriction>
            <owl:onProperty rdf:resource="&om;hasUnit"/>
            <owl:allValuesFrom>
              <owl:Class rdf:about="&om;LengthUnit"/>
            </owl:allValuesFrom>
          </owl:Restriction>	
        </owl:allValuesFrom>
      </owl:Restriction>     
    </rdfs:subClassOf>     
  </owl:Class>

So please represent all classes for units similarly.

2022-10-27 14:25 UTC, msff2 commented on JPS_Ontology/ontology/ontouom/MassPerEnergy
> +  </owl:Ontology>
Remove </owl:Ontology> from line 28.

2022-10-27 14:26 UTC, msff2 commented on JPS_Ontology/ontology/ontouom/HeatFluxDensity
> +  </owl:Ontology>
Remove </owl:Ontology> from line 28.

2022-10-28 04:55 UTC, YiKaiTsai commented
> How come JPS_Ontology/ontology/ontouom/MassPerEnergy is treated so differently from others, e.g. JPS_Ontology/ontology/ontouom/HeatFluxDensity? Shouldn't it also have a value and a unit, etc.?

MassPerEnergy was already defined in the original OM, but without a defined dimension. The massPerEnergy-Dimension was defined by us, and my intend was to append it to the MassPerEnergy definition as its defined dimension. I left out the MassPerEnergy value and unit parts, since they were already in OM. I could copy and paste the value and unit parts from OM into our file, if needed.

2022-10-28 16:47 UTC, sm453 approved these changes
All good. No need for further action regarding MassPerEnergy.

2022-10-31 02:01 UTC, merged