395 time series rdb connection
cambridge-cares/TheWorldAvatar pull request #397
Opened 2022-10-26 12:04 UTC by kokfoongcmcl

Externally, no change is required from codes using the TimeSeriesClient, all changes are internal.

Key changes:
1) RemoteRDBStoreClient no longer stores connection object, though at the moment there's no way of getting the privately stored "conn" variable, it's still best not to store it at all
2) Un-deprecated old time series methods without the connection argument, they all now work by opening a single connection using try-with-resource
3) Methods without the connection argument call the methods with the connection argument, thus removing code duplication
4) Renamed tests from deprecated to "WithoutConn"

Nice to haves but ignored in this PR due to time constraints at the time of writing:
- Tidy up tests, there may be some duplicates

2022-10-31 14:44 UTC, gpeb2 requested changes

2022-10-31 14:44 UTC, gpeb2 commented on JPS_BASE_LIB/src/main/java/uk/ac/cam/cares/jps/base/query/RemoteRDBStoreClient.java
> +        try (Connection conn = DriverManager.getConnection(this.rdbURL, this.rdbUser, this.rdbPassword);
Same as above.

2022-10-31 15:06 UTC, kokfoongcmcl commented on JPS_BASE_LIB/src/main/java/uk/ac/cam/cares/jps/base/timeseries/TimeSeriesClient.java
> +	"the RDB endpoint (URL, username and password) needs to be set in the constructor of TimeSeriesClient";
yes

2022-10-31 18:25 UTC, kokfoongcmcl commented on JPS_BASE_LIB/src/main/java/uk/ac/cam/cares/jps/base/timeseries/TimeSeriesClient.java
> +				rdbUrl = ""; // setting dummy url, is not used in practice anyway
Addressed by https://github.com/cambridge-cares/TheWorldAvatar/pull/397/commits/77b24f93b2c69ba21818d9165c52572d83e56afb and https://github.com/cambridge-cares/TheWorldAvatar/pull/397/commits/4cc5d30d3f2b167eae0da1c5580100082841d464

2022-10-31 18:26 UTC, kokfoongcmcl commented on JPS_BASE_LIB/src/main/java/uk/ac/cam/cares/jps/base/timeseries/TimeSeriesClient.java
> +			rdbURL = "";
Addressed by https://github.com/cambridge-cares/TheWorldAvatar/pull/397/commits/77b24f93b2c69ba21818d9165c52572d83e56afb and https://github.com/cambridge-cares/TheWorldAvatar/pull/397/commits/4cc5d30d3f2b167eae0da1c5580100082841d464

2022-10-31 18:29 UTC, kokfoongcmcl commented on JPS_BASE_LIB/src/main/java/uk/ac/cam/cares/jps/base/query/RemoteRDBStoreClient.java
> +                java.sql.ResultSet rs = stmt.executeQuery(query);
Addressed by https://github.com/cambridge-cares/TheWorldAvatar/pull/397/commits/379c623838c443e0a9965d65192f07a64edab4e4

2022-10-31 18:29 UTC, kokfoongcmcl commented on JPS_BASE_LIB/src/main/java/uk/ac/cam/cares/jps/base/query/RemoteRDBStoreClient.java
> +        try (Connection conn = DriverManager.getConnection(this.rdbURL, this.rdbUser, this.rdbPassword);
Addressed by https://github.com/cambridge-cares/TheWorldAvatar/pull/397/commits/20a7ade613b1bd16ea00aa46a54f960fceeb138b

2022-10-31 18:29 UTC, kokfoongcmcl commented on JPS_BASE_LIB/src/main/java/uk/ac/cam/cares/jps/base/query/RemoteRDBStoreClient.java
> +        try (Connection conn = DriverManager.getConnection(this.rdbURL, this.rdbUser, this.rdbPassword);
Addressed by https://github.com/cambridge-cares/TheWorldAvatar/pull/397/commits/20a7ade613b1bd16ea00aa46a54f960fceeb138b

2022-10-31 18:30 UTC, kokfoongcmcl commented on JPS_BASE_LIB/src/main/java/uk/ac/cam/cares/jps/base/query/RemoteRDBStoreClient.java
> +        try (Connection conn = DriverManager.getConnection(this.rdbURL, this.rdbUser, this.rdbPassword);
Addressed by https://github.com/cambridge-cares/TheWorldAvatar/pull/397/commits/20a7ade613b1bd16ea00aa46a54f960fceeb138b

2022-10-31 18:46 UTC, gpeb2 commented on JPS_BASE_LIB/src/main/java/uk/ac/cam/cares/jps/base/timeseries/TimeSeriesClient.java
> +			rdbURL = "";
Ideally the MockConnection class would be overridden to provide the required methods,

2022-10-31 18:47 UTC, gpeb2 commented on JPS_BASE_LIB/src/main/java/uk/ac/cam/cares/jps/base/timeseries/TimeSeriesClient.java
> +				rdbUrl = ""; // setting dummy url, is not used in practice anyway
See other comment https://github.com/cambridge-cares/TheWorldAvatar/pull/397#discussion_r1009750910

2022-11-01 10:26 UTC, kokfoongcmcl commented on JPS_BASE_LIB/src/main/java/uk/ac/cam/cares/jps/base/timeseries/TimeSeriesClient.java
> +				rdbUrl = ""; // setting dummy url, is not used in practice anyway
addressed in latest commits

2022-11-01 10:38 UTC, gpeb2 approved these changes

2022-11-01 10:45 UTC, merged