Dev met office agent within stack
cambridge-cares/TheWorldAvatar pull request #407
Opened 2022-10-31 11:47 UTC by markushofmeister

Enhanced the agent slightly based on learnings from the Derived Information Agent and added several (integration) tests. This agent "design" shall be used as blueprint for reworking the other agents for the King's Lynn use case.

2022-11-09 06:04 UTC, markushofmeister commented on Agents/MetOfficeAgent/agent/kgutils/tsclient.py
> +            conn.close()
Addressed by [71d6d8e](https://github.com/cambridge-cares/TheWorldAvatar/pull/407/commits/71d6d8ece6ca40ee001ae298de6f7a58f699d2b4)

2022-11-09 15:24 UTC, gpeb2 requested changes
Issues in the README. Particularly addressing the confusion between the Java Runtime Environment (JRE), used to run Java code, and the Java Development Kit (JDK), used to compile Java code.

2022-11-09 15:24 UTC, gpeb2 commented on Agents/MetOfficeAgent/README.md
>  [Java Runtime Environment version >=11]: https://adoptopenjdk.net/?variant=openjdk8&jvmVariant=hotspot
```suggestion
[Java Development Kit version >=11]: https://adoptopenjdk.net/?variant=openjdk8&jvmVariant=hotspot
```

2022-11-09 15:24 UTC, gpeb2 commented on Agents/MetOfficeAgent/README.md
> +3. Build latest *StackClient* JAVA resource, copy `.jar` file and entire `lib` folder into `<tmp_stack>` repository, and install resource for py4jps (Please note that this requires [Java Runtime Envi
```suggestion
3. Build latest *StackClient* JAVA resource, copy `.jar` file and entire `lib` folder into `<tmp_stack>` repository, and install resource for py4jps (Please note that this requires [Java Development Kit version >=11]):
```

2022-11-09 15:24 UTC, gpeb2 commented on Agents/MetOfficeAgent/README.md
> +This agent requires [JPS_BASE_LIB] and [Stack-Clients] to be wrapped by [py4jps]. Therefore, after installation of all required packages (incl. `py4jps >= 1.0.26`), the `StackClients` resource needs
```suggestion
This agent requires [JPS_BASE_LIB] and [Stack-Clients] to be wrapped by [py4jps]. Therefore, after installation of all required packages (incl. `py4jps >= 1.0.26`), the `StackClients` resource needs to be added to allow for access through `py4jps`. All required steps are detailed in the [py4jps] documentation. However, the commands provided below shall suffice to compile the latest `StackClients` resource locally and install it inside the Docker container using the provided [Dockerfile]. Please note, that compiling requires a [Java Development Kit version >=11]. *Updating the [JPS_BASE_LIB] resource is ONLY required if a pre-release version is needed, which is (currently) not the case for this agent.*
```

2022-11-09 15:24 UTC, gpeb2 commented on Agents/MetOfficeAgent/README.md
> +$ <github_personal_access_token>
Remove `$`s for consistency
```suggestion
docker login ghcr.io -u <github_username>
<github_personal_access_token>
```

2022-11-09 15:24 UTC, gpeb2 commented on Agents/MetOfficeAgent/README.md
> +Before starting development or spinning up the dockerized agent remotely, all required VSCode extensions shall be installed on the remote machine (e.g. *augustocdias.tasks-shell-input* or the *Python
```suggestion
Before starting development or spinning up the dockerized agent remotely, all required VSCode extensions shall be installed on the remote machine (e.g. *augustocdias.tasks-shell-input* or the *Python extension*). As the Docker image requires the [Stack-Clients] `.jar` file to be wrapped by [py4jps], it needs to be copied over manually to the respective folder as specified in the [Dockerfile] or can be created remotely by running the *Update JPSRM and Build and Debug* Debug Configuration. In order to build the resource, Java and Maven need to be available on the remote machine. In order to pull TWA specific Maven packages from the [Github package repository], `settings.xml` and `settings-security.xml` files need to be copied into Maven's `.m2` folder on the remote machine (typically located at user's root directory)
```

2022-11-10 01:35 UTC, markushofmeister commented
> Issues in the README. Particularly addressing the confusion between the Java Runtime Environment (JRE), used to run Java code, and the Java Development Kit (JDK), used to compile Java code.

Should be addressed by [b0e72ea](https://github.com/cambridge-cares/TheWorldAvatar/pull/407/commits/b0e72ea05888d0961809cb1ebb17a8eb3e140630)

2022-11-10 13:43 UTC, merged