Dev mods agent sensitivity analysis
cambridge-cares/TheWorldAvatar pull request #514
Opened 2022-12-07 15:53 UTC by cmclscourtney

adding sensitivity analysis to MoDS Simple Agent

2023-03-08 15:45 UTC, gpeb2 approved these changes

2023-03-08 15:50 UTC, gpeb2 requested changes
It would probably be better to have the save and load surrogate flags in the algorithm node, in case there are multiple surrogate algorithms. For the load flag this could be placed in an otherwise empty algorithm node.

2023-03-21 13:46 UTC, cmclscourtney commented
> It would probably be better to have the save and load surrogate flags in the algorithm node, in case there are multiple surrogate algorithms. For the load flag this could be placed in an otherwise empty algorithm node.

addressed in [f11af2a](https://github.com/cambridge-cares/TheWorldAvatar/pull/514/commits/f11af2adc6ec521e6f820ddfc3519458dd4ac7d7)

2023-05-05 14:54 UTC, gpeb2 approved these changes

2023-05-05 15:00 UTC, merged