Dev landregistry agent add derivation markup
cambridge-cares/TheWorldAvatar pull request #669
Opened 2023-03-21 15:56 UTC by markushofmeister

Added the required derivation markup functions for both `AverageSquareMetrePrice` and `PropertyValue` derivations. Tested both on some sample data with approx. 50 postcodes, approx. 420 buildings with sales transactions, and ultimately approx. 600 buildings with estimated property values. 

Everything seems to work fine, just three questions regarding the derivation update requests in the respective methods [here](https://github.com/cambridge-cares/TheWorldAvatar/blob/ea0709d51d18097f1bcae16c69526c2d14713df4/Agents/HMLandRegistryAgent/agent/datainstantiation/derivation_markup.py#L171) and [here](https://github.com/cambridge-cares/TheWorldAvatar/blob/ea0709d51d18097f1bcae16c69526c2d14713df4/Agents/HMLandRegistryAgent/agent/datainstantiation/derivation_markup.py#L346):

1) Should those updates be kept here or rather be removed (and only kept fo cases where actual markup changes) and the derivation cascade ultimately only be triggered by the FloodAssessmentAgent? Any experience/guidane?
2) If kept here, would you suggest to create the sync update on the spot using the `unifiedUpdateDerivation` or simply request the update and let the "heavy lifting" be done by the next asynchronous execution? (as expected, an update using `unifiedUpdateDerivation` will cause issues in case any of the registered agents is not available to compute the derivation on the spot)

2023-03-22 20:25 UTC, jb2197 commented
> Everything seems to work fine, just three questions regarding the derivation update requests in the respective methods [here](https://github.com/cambridge-cares/TheWorldAvatar/blob/ea0709d51d18097f1bcae16c69526c2d14713df4/Agents/HMLandRegistryAgent/agent/datainstantiation/derivation_markup.py#L171) and [here](https://github.com/cambridge-cares/TheWorldAvatar/blob/ea0709d51d18097f1bcae16c69526c2d14713df4/Agents/HMLandRegistryAgent/agent/datainstantiation/derivation_markup.py#L346):
> 
> 1. Should those updates be kept here or rather be removed (and only kept fo cases where actual markup changes) and the derivation cascade ultimately only be triggered by the FloodAssessmentAgent? Any experience/guidane?

I prefer to remove these updates - the design intention is to have the update on-demand upon accessing the information, so in my opinion it would be better to let FloodAssessmentAgent to trigger updates for those affected buildings.

2023-03-22 20:25 UTC, jb2197 requested changes

2023-03-23 16:42 UTC, CoMo-Group commented
> > Everything seems to work fine, just three questions regarding the derivation update requests in the respective methods [here](https://github.com/cambridge-cares/TheWorldAvatar/blob/ea0709d51d18097f1bcae16c69526c2d14713df4/Agents/HMLandRegistryAgent/agent/datainstantiation/derivation_markup.py#L171) and [here](https://github.com/cambridge-cares/TheWorldAvatar/blob/ea0709d51d18097f1bcae16c69526c2d14713df4/Agents/HMLandRegistryAgent/agent/datainstantiation/derivation_markup.py#L346):
> > 
> > 1. Should those updates be kept here or rather be removed (and only kept fo cases where actual markup changes) and the derivation cascade ultimately only be triggered by the FloodAssessmentAgent? Any experience/guidane?
> 
> I prefer to remove these updates - the design intention is to have the update on-demand upon accessing the information, so in my opinion it would be better to let FloodAssessmentAgent to trigger updates for those affected buildings.

Addressed by [61e7d36](https://github.com/cambridge-cares/TheWorldAvatar/pull/669/commits/61e7d36d0fac3bd08e351cb1e204a3ca542aab53) and [75bf8d2](https://github.com/cambridge-cares/TheWorldAvatar/pull/669/commits/75bf8d2a5aaec7dcec1d64cef30536477376cb45)

2023-03-23 16:43 UTC, markushofmeister commented on Agents/HMLandRegistryAgent/agent/datamodel/iris.py
> +
Addressed by [c843d87](https://github.com/cambridge-cares/TheWorldAvatar/pull/669/commits/c843d8749d6ef4a15516ae00547ca82ffa36ee83). Also amended for FloodWarningAgent  by [37c3198](https://github.com/cambridge-cares/TheWorldAvatar/pull/669/commits/37c31987dcefdb1a987f111ab084f9306b87cdf5)

2023-03-23 18:26 UTC, jb2197 approved these changes

2023-03-24 01:48 UTC, merged