dev-dtvf-patch-notes
cambridge-cares/TheWorldAvatar pull request #741
Opened 2023-05-10 16:56 UTC by mdhillman

This PR brings in changes to the DTVf including:

* A `CHANGELOG.md` file
* A distinct `VERSION` file
* New GitHub actions to:
  * Check the version number has been changed in a PR
  * Automated generation of release artifacts after a push to main
  * Automated generation of a release email after a push to main

2023-05-11 12:55 UTC, gpeb2 requested changes

2023-05-11 13:04 UTC, mdhillman commented on .github/scripts/dtvf/check-version.sh
> +# Get the VERSION file from the main branch of the repo, check that this new version does not match
Resolved.

2023-05-11 13:04 UTC, mdhillman commented on .github/workflows/release-dtvf.yml
> +          ./.github/scripts/dtvf/make-release-body.sh >> $HOME/body.md
Resolved.

2023-05-12 11:27 UTC, gpeb2 approved these changes

2023-05-12 11:28 UTC, merged