Draft: dev-dtvf-cesium-styling
cambridge-cares/TheWorldAvatar pull request #744
Opened 2023-05-11 16:10 UTC by mdhillman

This PR brings in a new version of the DTVF with the below changes:

- Cesium styling expressions can now be used in `data.json` file
  - Ths is detailed in the "Layers" section of the README in the example Cesium visualisation
  - Example Cesium visualisation has been updated with an example style expression
- Fixed issue with removing highlights on selected Cesium features

This PR has been marked as a draft whilst other DTVF PRs take precedence (#741 and #517)

2023-05-26 10:17 UTC, sm453 requested changes
Tested. Styling works fine.

One thing, though: The clipping planes side panel appears just fine in v3.4.0, but when upgrading to v3.5.0, everything appears bold and in the large heading font, and it is no longer functional. Is that simply because the changes from v3.4.0 have not been merged into this branch?

2023-06-15 10:46 UTC, jlai2021 commented
A newly reported issue, #791. This issue could potentially have an impact on our current testing. As such, I suggest we pause the testing process until this issue is properly addressed and resolved.

2023-06-26 08:59 UTC, mdhillman commented on web/digital-twin-vis-framework/CHANGELOG.md
>  * New clippling planes feature to allow `vertical` slicing of 3D tile sets.
Yes, will change.

2023-06-26 10:22 UTC, mdhillman commented
CSS issues causing clipping plane controls to disappear have now been resolved. Could @jlai2021 please test this an confirm at earliest convenience?

2023-06-26 15:29 UTC, sm453 requested changes
Tested again. Now everything works as expected, including the clipping planes.

2023-06-26 15:29 UTC, sm453 commented on web/digital-twin-vis-framework/example-cesium-vis/webspace/index.html
> +            MapHandler.MAP_API = "pk.eyJ1IjoiY21jbGlubm92YXRpb25zIiwiYSI6ImNrbGdqa3RoNDFnanIyem1nZXR3YzVhcmwifQ.hVk983r6YYlmFE8kSMbzhA";
Please remove user and API key.

2023-06-28 13:16 UTC, mdhillman commented on web/digital-twin-vis-framework/example-cesium-vis/webspace/index.html
> +            MapHandler.MAP_API = "pk.eyJ1IjoiY21jbGlubm92YXRpb25zIiwiYSI6ImNrbGdqa3RoNDFnanIyem1nZXR3YzVhcmwifQ.hVk983r6YYlmFE8kSMbzhA";
Now resolved.

2023-06-28 13:35 UTC, sm453 approved these changes

2023-06-28 14:01 UTC, merged