dev-ifc2ontobim-agent-add-address
cambridge-cares/TheWorldAvatar pull request #787
Opened 2023-06-13 09:26 UTC by qhouyee

Added the instantiation of addresses for Pirmasens and Singapore into the icontact:Address format.
Bug fix for namespace error when directly using the IfcOwl TTL file for conversion instead of the IFC model.

2023-06-15 15:08 UTC, sm453 requested changes
Could you please also revise the IfcOwlConverter readme file to account for this way of building the images? It currently says "Please build the image for this agent and then proceed to the other agent...". It should say something like "Even though you can build the image for this agent individually, there is no need to do so. You can proceed directly to the other agent...".

2023-06-15 16:23 UTC, sm453 commented
Also, it seems like the agent is _deleting_ the `ttl` file from the `data` folder after a successful upload. It would be useful to put a (big, fat) warning in the readme file that it does that. Or am I going crazy?

2023-06-19 08:12 UTC, qhouyee commented on Agents/Ifc2OntoBIMAgent/README.md
> +- There is no need to set up the [IfcOwlConverterAgent](https://github.com/cambridge-cares/TheWorldAvatar/tree/main/Agents/IfcOwlConverterAgent) separately.
Have updated the instructions for both agents as per comments in the latest commit

2023-06-19 08:20 UTC, qhouyee commented
> Also, it seems like the agent is _deleting_ the `ttl` file from the `data` folder after a successful upload. It would be useful to put a (big, fat) warning in the readme file that it does that. Or am I going crazy?

Have added a warning to the README, and indicated that a TTL file for OntoBIM ABox is never generated during this process.

2023-06-19 09:27 UTC, sm453 approved these changes

2023-06-19 09:51 UTC, merged