dev-main-readme
cambridge-cares/TheWorldAvatar pull request #822
Opened 2023-07-06 10:10 UTC by mdhillman

This PR brings in an overhaul to the content of the top-level README file within the repository, hopefully bringing it more in line with other popular open source projects.

This includes a short recap of the recently added "Key features" sections (I felt using it verbatim would lead to an overly long document). However, the full text has been added to the main page of the Wiki, which is now linked to from the README.

Note that this PR will need @mk306-como's approval of the new TWA logo before it can be merged.

2023-07-06 10:28 UTC, sm453 requested changes

2023-07-06 10:28 UTC, sm453 commented on README.md
> +The World Avatar project aims to create a digital ‘avatar’ of the real world. The digital world is composed of a dynamic knowledge graph (KG) that contains concepts and data that describe the world,
Please re-add the full stop. We do need it. ;-)

2023-07-06 10:28 UTC, sm453 commented on README.md
> +**Intelligent Agents:**<br/>
The word "intelligent" in this context is loaded. I would go for something less controversial like "autonomous".

2023-07-06 10:28 UTC, sm453 commented on README.md
> +Listed below are a number of the key technical features available within The World Avatar ecosystem. More information on these, and other features, can be see on [The World Avatar Wiki](https://githu
"can be seen"

2023-07-07 10:01 UTC, mdhillman commented on README.md
> +Listed below are a number of the key technical features available within The World Avatar ecosystem. More information on these, and other features, can be see on [The World Avatar Wiki](https://githu
Addressed in new commit.

2023-07-07 10:02 UTC, mdhillman commented
Given my history with typos, it _might_ be worthwhile seeing if there's an off-the-shelf spell/grammar checking (with a configurable dictionary) action we can automate.

2023-07-11 08:54 UTC, sm453 commented
> Note that this PR will need @mk306-como's approval of the new TWA logo before it can be merged. Until this time, the PR will be marked as a draft.

Having discussed this amongst a few of us, we believe the most sensible way forward may be to just remove the logo from this PR and merge it, given that it is highly uncertain when/if we get feedback on the logo.

2023-07-11 09:03 UTC, sm453 commented
Change of plan: @mk306-como just approved the logo! :-)

2023-07-11 09:48 UTC, sm453 approved these changes

2023-07-11 09:49 UTC, merged