963 filter agent
cambridge-cares/TheWorldAvatar pull request #964
Opened 2023-10-12 09:54 UTC by cmclscourtney

Filter agent with configurable query
- [ ] Get config from stack to get endpoints
- [ ] Document 
- [ ] Include config that uses with stack

2023-10-17 11:09 UTC, cmclscourtney commented
Nice to have if time

- [ ] enforce literal only filtering
- [ ] read query into builder
- [ ] if correct filters not used return sensible error
- [ ] optionally provide config to name queries and set default values
- [ ] discover Blazegraph endpoints (sim to FIA)
- [ ] walk file tree to discover queries

2023-10-27 10:40 UTC, qhouyee approved these changes

2023-10-27 16:26 UTC, gpeb2 requested changes
Please test my suggestions.

2023-10-27 16:26 UTC, gpeb2 commented on Agents/FilterAgent/filter-agent/src/main/java/com/cmclinnovations/filteragent/FilterAgentApplication.java
> +	RemoteStoreClient remoteStoreClient;
```suggestion
	private BlazegraphClient blazegraphClient;
	private RemoteStoreClient remoteStoreClient;
```

2023-10-27 16:26 UTC, gpeb2 commented on Agents/FilterAgent/filter-agent/src/main/java/com/cmclinnovations/filteragent/FilterAgentApplication.java
> +	public String filter(@RequestParam("subs") String substitutionString,
```suggestion
	public String filter(@RequestParam("subs") Map<String, String> subsMap,
```

2023-10-27 16:26 UTC, gpeb2 commented on Agents/FilterAgent/filter-agent/src/main/java/com/cmclinnovations/filteragent/FilterAgentApplication.java
> +				});
```suggestion
```

2023-10-27 19:14 UTC, cmclscourtney commented on Agents/FilterAgent/filter-agent/src/main/java/com/cmclinnovations/filteragent/FilterAgentApplication.java
> +	RemoteStoreClient remoteStoreClient;
resolved by d957cc7

2023-10-27 19:16 UTC, cmclscourtney commented
Make sure to remove **ALL** `-SNAPSHOT` flags

2023-10-30 14:55 UTC, cmclscourtney commented on Agents/FilterAgent/filter-agent/src/main/java/com/cmclinnovations/filteragent/FilterAgentApplication.java
> +				});
moved inside constructor in 7a07b45

2023-10-30 16:27 UTC, gpeb2 approved these changes

2023-10-30 16:41 UTC, merged