865-DataSubset-split-to-Load/Process/Layer
cambridge-cares/TheWorldAvatar pull request #970
Opened 2023-10-17 15:49 UTC by Ushcode

Addressing issue #865, this PR implements a refactor of  `PostgresDataSubSet` class as well ats its children to allow a `dataSubset` to be specified without a subdirectory. This means that SQL post processing and GeoServer uploading can happen independently of data upload and arbitrary action can be performed on prior uploaded data.

`TBoxCSV` and `RDF` data are still required to specify a subdirectory, while `PostGresDataSubset` and its children: `Tabular`, `GeoServerDataSubset`, `Vector` and `Raster` will all proceed with a warning that no subdirectory is specified.

Correct behaviour of these changes was tested and output logs of the uploads are attached to this PR

# RDF error

15:31:40.820 [main] DEBUG org.eclipse.jetty.util.component.AbstractLifeCycle - STOPPED com.bigdata.rdf.sail.webapp.client.AutoCloseHttpClient@3ef41c66
Exception in thread "main" java.lang.RuntimeException: No Subdirectory Specified - required for RDF data
        at com.cmclinnovations.stack.clients.core.datasets.RDF.loadInternal(RDF.java:18)
        at com.cmclinnovations.stack.clients.core.datasets.DataSubset.load(DataSubset.java:55)
        at com.cmclinnovations.stack.clients.core.datasets.DatasetLoader.lambda$loadData$6(DatasetLoader.java:142)
        at java.base/java.util.ArrayList.forEach(Unknown Source)
        at com.cmclinnovations.stack.clients.core.datasets.DatasetLoader.loadData(DatasetLoader.java:142)
        at java.base/java.util.Iterator.forEachRemaining(Unknown Source)
        at com.cmclinnovations.stack.clients.core.datasets.DatasetLoader.uploadInputDatasets(DatasetLoader.java:61)
        at com.cmclinnovations.stack.DataUploader.main(DataUploader.java:12)
 
# TBoxCSV error

15:33:34.413 [main] DEBUG org.eclipse.jetty.util.component.AbstractLifeCycle - STOPPED SslContextFactory@58740366(null,null)
15:33:34.413 [main] DEBUG org.eclipse.jetty.util.component.AbstractLifeCycle - STOPPED com.bigdata.rdf.sail.webapp.client.AutoCloseHttpClient@30ca0779
Exception in thread "main" java.lang.RuntimeException: No subdirectory specified - required for TBoxCSV data
        at com.cmclinnovations.stack.clients.core.datasets.TBoxCSV.loadInternal(TBoxCSV.java:32)
        at com.cmclinnovations.stack.clients.core.datasets.DataSubset.load(DataSubset.java:55)
        at com.cmclinnovations.stack.clients.core.datasets.DatasetLoader.lambda$loadData$6(DatasetLoader.java:142)
        at java.base/java.util.ArrayList.forEach(Unknown Source)
        at com.cmclinnovations.stack.clients.core.datasets.DatasetLoader.loadData(DatasetLoader.java:142)
        at java.base/java.util.Iterator.forEachRemaining(Unknown Source)
        at com.cmclinnovations.stack.clients.core.datasets.DatasetLoader.uploadInputDatasets(DatasetLoader.java:61)
        at com.cmclinnovations.stack.DataUploader.main(DataUploader.java:12)

2023-10-17 16:02 UTC, Ushcode reviewed
# Routing stack

Everything uploads and processes correctly, following warning is present in console:

```15:55:05.445 [main] WARN com.cmclinnovations.stack.clients.core.datasets.PostgresDataSubset - No Subdirectory specified, Continuing with SQL process and creation without data upload```

2023-10-26 14:47 UTC, gpeb2 requested changes
I've made some some suggestions, happy to discuss them.

2023-10-26 14:47 UTC, gpeb2 commented on Deploy/stacks/dynamic/stack-data-uploader/README.md
>          polygon.geojson # Data file
```suggestion
      datasubset1/     # Data subdirectory for data subset1
        data.csv        # Data file for dataset1
    dataset2/           # Data directory for dataset2
      datasubset2/      # Data subdirectory for data subset2
        polygon.geojson # Data file for dataset2
```

2023-10-26 14:47 UTC, gpeb2 commented on Deploy/stacks/dynamic/stack-clients/src/main/java/com/cmclinnovations/stack/clients/core/datasets/PostgresDataSubset.java
> +            loadData(dataSubsetDirectory, database, database);
```suggestion
            loadData(dataSubsetDirectory, database, parent.baseIRI());
```

2023-10-26 14:47 UTC, gpeb2 commented on Deploy/stacks/dynamic/stack-clients/src/main/java/com/cmclinnovations/stack/clients/core/datasets/RDF.java
> +            throw new RuntimeException("No Subdirectory Specified - required for RDF data");
```suggestion
            throw new RuntimeException("No 'subdirectory' specified - required for RDF data");
```

2023-10-26 14:47 UTC, gpeb2 commented on Deploy/stacks/dynamic/stack-clients/src/main/java/com/cmclinnovations/stack/clients/core/datasets/TBoxCSV.java
> +            throw new RuntimeException("No subdirectory specified - required for TBoxCSV data");
```suggestion
            throw new RuntimeException("No 'subdirectory' specified - required for TBoxCSV data");
```

2023-10-27 15:47 UTC, gpeb2 approved these changes

2023-10-27 16:25 UTC, merged